### ISSUE TITLE
TODO for CRS changes

### ISSUE THREAD

**Issue by rsbivand** [edzer/sp#68]
to roll out new **sp** and **rgdal**, the next things have to be done

- [x] compare reverse dependencies against sp & rgdal released RSB GDAL 2.4.4 PROJ 5.2.0
- [x] compare reverse dependencies against sp & rgdal devel RSB GDAL 3.0.3/PROJ 6.3.0 ([st_630_303_200117.zip](https://github.com/edzer/sp/files/4076939/st_630_303_200117.zip))
- [x] ?check against PROJ 7 release candidates
- [x] submit to CRAN
- [x] contribute to **sf** r-spatial blog https://github.com/r-spatial/sf/issues/1244
- [x] inform twitter

**Comment by edzer** [comment]
OK, did you make a PR against sp, or shall I do that? Do they have to be rolled out in a particular order?

**Comment by rsbivand** [comment]
No, I think you picked up my commits from my fork master and applied them to the master by https://github.com/edzer/sp/commit/74a878034018b57e70bf57d1979d29588ff5a835, didn't you?

**Comment by edzer** [comment]
Ah, thanks, yes, I forgot.

**Comment by rsbivand** [comment]
And https://github.com/edzer/sp/commit/3e0497ba1206f0aaf8f691c81acfbb38debeecfc before that (for the record).

**Comment by rsbivand** [comment]
Can we try to release **sp** with my fork commits of 21 January, which should have benign effects on **rgdal** and **raster** and their revdeps? Then it will be easier to move to releasing GDAL3-ready **rgdal**. On PROJ6/GDAL3, I'm seeing about 50 new breakages across the whole revdep tree of ~ 900 packages, mostly messing with sp::CRS/raster::crs objects internally and not using accessor functions. All warned, many have reported back that problem fixed but not released to CRAN.

**Comment by edzer** [comment]
Yes, that means releasing from my master current branch, right?

**Comment by rsbivand** [comment]
Yes, please check my PRs. Maybe an RC of **sp**, so that you or I can check **rgdal** rev. 938.

**Comment by edzer** [comment]
Thanks; merged, and I bumped the version to 1.4-0.

**Comment by edzer** [comment]
While checking, I see
```
* checking dependencies in R code ... NOTE
Missing or unexported objects:
  ‘rgdal::checkCRSArgs_ng’ ‘rgdal::new_proj_and_gdal’
```
is some version of rgdal required that is not yet on CRAN? (How) can we suppress this NOTE?

**Comment by rsbivand** [comment]
This is the circular dependency problem, **sp** needing unreleased **rgdal** needs to be on CRAN first. I think we saw this earlier (maybe an **sf** issue)? I think we agreed to include this as a note to CRAN-team that the NOTE would be resolved when **rgdal** was released?

**Comment by rsbivand** [comment]
I'm still seeing 1.3-4 after `git fetch upstream` - have you pushed?

**Comment by edzer** [comment]
Sorry, now I have.

**Comment by edzer** [comment]
While checking on the gdal 3.0.4/proj 7.0.0RC1/geos 3.8.0 image I see lots of these warning messages:
```
< 8: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
<   Discarded datum Unknown based on Bessel 1841 ellipsoid in CRS definition
```
with
```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rgdal_1.5-5 sp_1.3-2   

loaded via a namespace (and not attached):
[1] compiler_3.6.2  grid_3.6.2      lattice_0.20-38
```

**Comment by rsbivand** [comment]
This is as expected, they come from inside **rgdal**, where there are also tools to moderate the numbers of warnings. In **rgdal**, I have `set_thin_PROJ6_warnings(TRUE)` at the beginning of `examples{}` sections in help files where needed, but not in tests/*.R. Without the warnings, I can't check back for possible impacts in *.Rcheck/*-EX.Rout files, but maybe that doesn't matter.

**Comment by rsbivand** [comment]
Is `sp_1.3-2` attached reliable??

**Comment by rsbivand** [comment]
I see "Discarded" in tests/fail1.Rout and tests/pass1.Rout, as well as man pages for: CRS-class, degAxis, gridlines, loadMeuse, meuse, meuse.grid, recenter-methods, spChFIDs-methods, spDistsN1, spplot. None I can see in vignettes. To turn on thinning, would need to test for **rgdal**, its version, and whether GDAL & PROJ are NG.

**Comment by edzer** [comment]
Sorry, this was with sp 1.4-0 (posted the wrong sessionInfo()).

**Comment by rsbivand** [comment]
1.4-0 1 NOTE with devel (excess time when run with --run-donttest --run-dontrun), so OK otherwise, and **rgdal** 1.5-5.

**Comment by edzer** [comment]
OK, then I will submit with the message:
* expect a NOTE from rgdal, that will go away with new rgdal which needs this sp version
* expect several packages that will break, but all have been informed timely.

**Comment by edzer** [comment]
Submitted.
